name: Security Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # Run weekly on Monday at 3 AM UTC
  workflow_dispatch:

jobs:
  security-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]

      - name: Run Bandit security scan
        run: bandit -c pyproject.toml -r flrts_extensions/ -f json -o bandit-report.json || true

      - name: Display Bandit results
        run: bandit -c pyproject.toml -r flrts_extensions/ -f screen

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.json
          retention-days: 90
