name: Security Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 3 * * 1'  # Run weekly on Monday at 3 AM UTC
  workflow_dispatch:

jobs:
  security-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml]

      - name: Run Bandit security scan
        run: bandit -c pyproject.toml -r flrts_extensions/ -f json -o bandit-report.json || true

      - name: Display Bandit results
        if: always()
        run: bandit -c pyproject.toml -r flrts_extensions/ -f screen || true

      - name: Check for high-severity issues
        if: always()
        run: |
          if [ -f bandit-report.json ]; then
            HIGH_COUNT=$(jq '[.results[] | select(.issue_severity == "HIGH" or .issue_severity == "CRITICAL")] | length' bandit-report.json)
            echo "Found $HIGH_COUNT high/critical severity issues"
            if [ "$HIGH_COUNT" -gt 0 ]; then
              echo "❌ CRITICAL/HIGH severity security issues found - failing workflow"
              exit 1
            else
              echo "✅ No critical/high severity issues found"
            fi
          fi

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: bandit-report.json
          retention-days: 90
